### PR TITLE
#99 adding pictures to fix --image not found -- issue.

### PR DESCRIPTION
**Pull request by ashwini3326**
Adding some image file to fix the issue https://github.com/RedHatOfficial/GoCourse/issues/99 . PTAL

Source :- 
[images/computer_latency_1.jpg]( https://unsplash.com/photos/7PSKG7iAh7g/)
[images/computer_latency_2.png]( https://developers.redhat.com/sites/default/files/blog/2016/02/will-cohen-blog_graphics-02-300x300.png)
[images/perf.jpg](https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80)

[images/interface.svg](https://github.com/MariaLetta/free-gophers-pack/blob/master/illustrations/svg/21.svg)
[images/teams.png](https://github.com/MariaLetta/free-gophers-pack/blob/master/illustrations/christmas%20illustrations/png/2.png)

### CODE REVIEW

**Comment by ashwini3326** [comment]
PTAL

**Comment by tisnik** [comment]
do you know about any licenses/copyright for those images @ashwini3326 ? We need to make sure not to use any copyrighted material

**Comment by ashwini3326** [comment]
I have mentioned the links of the images, two of them is free image from unsplash, one is from redhat developer blog, and other 2 is a public github repo.

**Comment by tisnik** [comment]
> I have mentioned the links of the images, two of them is free image from unsplash, one is from redhat developer blog, and other 2 is a public github repo.

ok nice!

**Pull request merged**
